#!../../bin/linux-x86_64/test-irio
#+======================================================================
# $HeadURL: https://svnpub.codac.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/tags/CODAC-CORE-7.1A1/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 127616 2022-01-03 12:25:45Z kimh19 $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2022 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

< envPaths
< envSystem
< envUser

cd "${TOP}"

############################################################################
## Register all support components
############################################################################

dbLoadDatabase "dbd/test-irio.dbd"
test_irio_registerRecordDeviceDriver pdbbase

< "${TOP}/iocBoot/ioctest-irio/sddPreDriverConf.cmd"
< "${TOP}/iocBoot/ioctest-irio/userPreDriverConf.cmd"
< "${TOP}/iocBoot/ioctest-irio/threadSchedulingConf.cmd"
< "${TOP}/iocBoot/ioctest-irio/dbToLoad.cmd"
< "${TOP}/iocBoot/ioctest-irio/ioctest-irio-preSaveRestore.cmd"

############################################################################
## IOC Logging
############################################################################
iocLogInit
iocLogPrefix "${STY} : "

############################################################################
## IOC initialization
############################################################################
cd "${TOP}/db"
iocInit

< "${TOP}/iocBoot/ioctest-irio/ioctest-irio-postSaveRestore.cmd"
< "${TOP}/iocBoot/ioctest-irio/sddSeqToLoad.cmd"
< "${TOP}/iocBoot/ioctest-irio/seqToLoad.cmd"
< "${TOP}/iocBoot/ioctest-irio/sddPostDriverConf.cmd"
< "${TOP}/iocBoot/ioctest-irio/userPostDriverConf.cmd"


dbl > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbl"
dbla > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbla"
dbior > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbior"
dbhcr > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbhcr"

#- End-of-file marker - do not delete or add lines below!
